### ISSUE TITLE
Can not build devcontainer: Operation not permitted

### ISSUE THREAD

**Issue by moi90** [maresb/micromamba-devcontainer#17]
I can not build the devcontainer which I created using `cruft create https://github.com/maresb/cookiecutter-micromamba-devcontainer`:

```
 => [ 5/13] RUN :     && micromamba config append channels conda-forge     0.5s
 => => # terminate called after throwing an instance of 'std::system_error'    
 => => #   what():  Operation not permitted     
```

I tried to comment out the this step to see how far it gets, but then, the following `pipx install` step fails. 

VS Code log file: [remoteContainers-2023-06-27T08-49-37.276Z.log](https://github.com/mamba-org/micromamba-devcontainer/files/11879750/remoteContainers-2023-06-27T08-49-37.276Z.log)

```
Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:25.715Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.15.0-75-generic
```

Interestingly, even running the bare docker image does not work:

```
$ docker run --rm -it ghcr.io/mamba-org/micromamba-devcontainer:git-d175103
Unable to find image 'ghcr.io/mamba-org/micromamba-devcontainer:git-d175103' locally
git-d175103: Pulling from mamba-org/micromamba-devcontainer
[...]
Digest: sha256:fb56b66c8993ee752840daa5b9cfdaff6e53a089bafae858b92870a9cd05c3d8
Status: Downloaded newer image for ghcr.io/mamba-org/micromamba-devcontainer:git-d175103
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
/usr/local/bin/_activate_current_env.sh: line 35:    14 Aborted                 (core dumped) micromamba activate "${ENV_NAME}"
```

**Comment by maresb** [comment]
Hey @moi90, sorry about the trouble. Could you please instead try with https://github.com/maresb/micromamba-devcontainer-example?

The devcontainer currently requires a Python project with a `pyproject.toml` and a `conda-lock.yml`, as is provided in the example. I need to update the docs to reflect this.

**Comment by moi90** [comment]
I tried with the vanilla example and it is the same:

```
 => [ 4/13] COPY --chown=mambauser:mambauser conda-lock.yml /tmp/conda-lo  0.0s
 => ERROR [ 5/13] RUN :     && micromamba config append channels conda-fo  0.7s
                                                                                
                                                                                
------
 > [ 5/13] RUN :     && micromamba config append channels conda-forge     && micromamba install --yes --name base         --category dev --category main --file /tmp/conda-lock.yml     && micromamba clean --all --yes ;:
#10 0.568 terminate called after throwing an instance of 'std::system_error'
#10 0.568   what():  Operation not permitted
#10 0.692 bash: line 1:     7 Aborted                 (core dumped) micromamba config append channels conda-forge
------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/usr/local/bin/_dockerfile_shell.sh :     && micromamba config append channels conda-forge     && micromamba install --yes --name base         --category dev --category main --file /tmp/conda-lock.yml     && micromamba clean --all --yes ;]: exit code: 134
[2023-06-27T10:47:15.570Z] Stop (1858 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /home/moi/Development/micromamba-devcontainer/micromamba-devcontainer-example/.devcontainer/dev.Dockerfile -t vsc-micromamba-devcontainer-example-0891a3923a2acd3ee55474fde48bd76a --build-arg CONTAINER_WORKSPACE_FOLDER=/workspaces/micromamba-devcontainer-example /home/moi/Development/micromamba-devcontainer/micromamba-devcontainer-example
[2023-06-27T10:47:15.572Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /home/moi/Development/micromamba-devcontainer/micromamba-devcontainer-example/.devcontainer/dev.Dockerfile -t vsc-micromamba-devcontainer-example-0891a3923a2acd3ee55474fde48bd76a --build-arg CONTAINER_WORKSPACE_FOLDER=/workspaces/micromamba-devcontainer-example /home/moi/Development/micromamba-devcontainer/micromamba-devcontainer-example
[2023-06-27T10:47:15.573Z]     at HS (/home/moi/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:256:1490)
[2023-06-27T10:47:15.573Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-06-27T10:47:15.573Z]     at async Cu (/home/moi/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:255:2801)
[2023-06-27T10:47:15.573Z]     at async Zw (/home/moi/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:255:1779)
[2023-06-27T10:47:15.573Z]     at async KS (/home/moi/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:261:2006)
[2023-06-27T10:47:15.574Z]     at async co (/home/moi/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:261:3110)
[2023-06-27T10:47:15.574Z]     at async LP (/home/moi/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:360:9352)
[2023-06-27T10:47:15.574Z]     at async DP (/home/moi/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js:360:9108)
[2023-06-27T10:47:15.580Z] Stop (2262 ms): Run: /usr/share/code/code /home/moi/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/moi/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/moi/Development/micromamba-devcontainer/micromamba-devcontainer-example --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/moi/Development/micromamba-devcontainer/micromamba-devcontainer-example --log-level debug --log-format json --config /home/moi/Development/micromamba-devcontainer/micromamba-devcontainer-example/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-06-27T10:47:15.580Z] Exit code 1
[2023-06-27T10:47:15.588Z] Command failed: /usr/share/code/code /home/moi/.vscode/extensions/ms-vscode-remote.remote-containers-0.245.2/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/moi/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /home/moi/Development/micromamba-devcontainer/micromamba-devcontainer-example --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/moi/Development/micromamba-devcontainer/micromamba-devcontainer-example --log-level debug --log-format json --config /home/moi/Development/micromamba-devcontainer/micromamba-devcontainer-example/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-06-27T10:47:15.588Z] Exit code 1
```

> The devcontainer currently requires a Python project with a `pyproject.toml` and a `conda-lock.yml`, as is provided in the example. I need to update the docs to reflect this.

Yes, I have already stumbled upon this, but then created the files.

I suspect something to be wrong with the base image as this doesn't work, either (see above).

**Comment by maresb** [comment]
Thanks a lot for the details. What's your host operating system?

**Comment by moi90** [comment]
The host is:

```
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu4-noarch:printing-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

**Comment by maresb** [comment]
Ok, that should work fine.

And to confirm, if you clone https://github.com/maresb/micromamba-devcontainer-example, open it with VS Code, reopen in a devcontainer, then you get the error?

**Comment by moi90** [comment]
> And to confirm, if you clone https://github.com/maresb/micromamba-devcontainer-example, open it with VS Code, reopen in a devcontainer, then you get the error?

That is correct :)

![grafik](https://github.com/mamba-org/micromamba-devcontainer/assets/332746/fe529b00-c832-41fc-98ed-9f3b27d21762)

**Comment by maresb** [comment]
Does it work one base image up? The activation is from [here](https://github.com/mamba-org/micromamba-docker/blob/main/_activate_current_env.sh)

In other words, does the following succeed?

```bash
docker run --rm -it mambaorg/micromamba:git-4073267-jammy
```

**Comment by moi90** [comment]
No, that also does not work (on two different Linux machines):

```
$ docker run --rm -it mambaorg/micromamba:git-4073267-jammy
Unable to find image 'mambaorg/micromamba:git-4073267-jammy' locally
git-4073267-jammy: Pulling from mambaorg/micromamba
6b851dcae6ca: Pull complete 
35fc687ae334: Pull complete 
47d31fc91e93: Pull complete 
4f4fb700ef54: Pull complete 
17c3c52d8169: Pull complete 
515324ab4149: Pull complete 
e2160265fc08: Pull complete 
8856d51f2e95: Pull complete 
2302e9d88a83: Pull complete 
2c67d8a026d2: Pull complete 
Digest: sha256:77dd2668aecff2383270a72fc0827c68aabe1cad3f01f3a3f5977665bb5bed70
Status: Downloaded newer image for mambaorg/micromamba:git-4073267-jammy
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
/usr/local/bin/_activate_current_env.sh: line 35:    14 Aborted                 (core dumped) micromamba activate "${ENV_NAME}"
```

**Comment by moi90** [comment]
My error seems to be the same as this one: https://github.com/mamba-org/micromamba-docker/issues/211

I followed the [official installation guide](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) to upgrade docker.
It is now the latest version (`docker-ce (5:24.0.2-1~ubuntu.22.04~jammy`) and the base image works:

```
$ docker run --rm -it mambaorg/micromamba:git-4073267-jammy
(base) mambauser@9ad8b7d86772:/tmp$ 
```

Building the devcontainer image still does not work, however. Instead of failing, it now hangs indefinitely at the following stage:

```
=> [ 5/13] RUN :     && micromamba config append channels conda-forge    40.6s
 => => #   Summary:                                                            
 => => #   Install: 114 packages                                               
 => => #   Total download: 0 B                                                 
 => => # ──────────────────────────────────────────────────────────────────────
 => => # ────────────────                                                      
 => => # Transaction starting                                                  
```

(I would assume that my internet connection is just slow, but it says "Total download: 0 B" and nothing happened for roughly an hour.)

**Comment by maresb** [comment]
Very nice work! This is definitely progress.

The thing with `0 B` as total download is a bug in the Micromamba output. The download is fairly sizeable, and it pauses exactly there, but I'd expect it to be several minutes but I think your internet would have to be really slow for it to be an hour. (But then again with German Dienstanbietern... :roll_eyes:)

**Comment by moi90** [comment]
Everything now works, thank you very much!

So, in total, only an up-to-date Docker installation was required :)

**Comment by maresb** [comment]
Wonderful!!!

What was the issue with being stalled on "Transaction starting"? Did you just have to wait longer? Around how much time did you end up waiting in the end?

**Comment by moi90** [comment]
I think it really was my internet connection that evening. And I might have directly tried it with the target project (not the example) which installs PyTorch and the like.
