### ISSUE TITLE
Permission denied error when running `pre-commit`

### ISSUE THREAD

**Issue by jtpio** [maresb/micromamba-devcontainer#2]
Trying to use this devcontainer on a project also using `pre-commit`.

Getting the following error when committing changes, or running `pre-commit` manually:

```
An unexpected error has occurred: PermissionError: [Errno 13] Permission denied: '/mnt/cache'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/opt/conda/lib/python3.10/site-packages/pre_commit/main.py", line 340, in main
    store = Store()
  File "/opt/conda/lib/python3.10/site-packages/pre_commit/store.py", line 51, in __init__
    os.makedirs(self.directory, exist_ok=True)
  File "/opt/conda/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/mnt/cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/pre-commit", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/pre_commit/main.py", line 337, in main
    with error_handler(), logging_handler(args.color):
  File "/opt/conda/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/conda/lib/python3.10/site-packages/pre_commit/error_handler.py", line 81, in error_handler
    _log_and_exit(msg, ret_code, e, traceback.format_exc())
  File "/opt/conda/lib/python3.10/site-packages/pre_commit/error_handler.py", line 31, in _log_and_exit
    storedir = Store().directory
  File "/opt/conda/lib/python3.10/site-packages/pre_commit/store.py", line 51, in __init__
    os.makedirs(self.directory, exist_ok=True)
  File "/opt/conda/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/mnt/cache'
```

After briefly looking at the source, it might be related to the following logic:

https://github.com/mamba-org/micromamba-devcontainer/blob/e56c5fc7a6d0283b4489f9428d74abe0f7b19a65/Dockerfile#L171-L177

This is reproducible by creating a Codespace from https://github.com/maresb/micromamba-devcontainer-example:

![image](https://user-images.githubusercontent.com/591645/185502561-8853ec50-b8af-4f3f-ad55-bd6125eb94eb.png)

![image](https://user-images.githubusercontent.com/591645/185502420-2ca33869-82d9-4bc3-985a-b081b2a486b5.png)

**Comment by maresb** [comment]
Ah, I see...

Thanks so much for all the detail! I particularly appreciate you showing me where to click to create a codespace.

For my local use cases, I have been bind mounting the cache directories according to [this](https://github.com/maresb/micromamba-devcontainer-example/blob/c92a4daccee666002db5802a88f050d446be9b63/.devcontainer/devcontainer.json#L25). Since I run multiple devcontainers, I was worried about conflicts if I used a named volume.

But thinking about it again, we could probably use an anonymous volume by putting `VOLUME /mnt/cache` in the Dockerfile. Anyways, that would be much more elegant than the bind mount.

Does that sound like a good approach? We'll need to test it first (and we should really set up automated tests...).

**Comment by jtpio** [comment]
Thanks @maresb, sounds like something to try yes!

**Comment by maresb** [comment]
I ended up deciding against the anonymous volume, and went with named volumes instead.

It should be fixed now. Could you please reload the codespace and try again to confirm?

**Comment by jtpio** [comment]
Thanks @maresb.

This seems to work well with the example repo now: https://github.com/maresb/micromamba-devcontainer-example

![image](https://user-images.githubusercontent.com/591645/185883009-66602175-da1f-4d55-b65d-2438f2a2c18d.png)

I'll try again with the other repo and report if there is any other issue.

Thanks!
